### ISSUE TITLE
`Error: Cannot find module './Arc'` when upgrading to v1.1.2 or v1.1.3

### ISSUE THREAD

**Issue by gaurav** [keesey/newick-js#4]
Hi there! I don't have a ton of experience with CommonJS and ES6 differences, so I might be doing something dumb here. Until newick-js v1.1.1, I can load the `parse()` function from newick-js from within my CommonJS program by using:

```
const parseNewick = require('newick-js').parse;
```

If I try doing this with newick-js v1.1.2 or v1.1.3, I get the following error:

```
Error: Cannot find module './Arc'
Require stack:
- /Users/gaurav/Development/phyloref/phyx.js/node_modules/newick-js/dist/index.js
- /Users/gaurav/Development/phyloref/phyx.js/src/wrappers/PhylogenyWrapper.js
- /Users/gaurav/Development/phyloref/phyx.js/src/index.js
- /Users/gaurav/Development/phyloref/phyx.js/test/citations.js
- /Users/gaurav/Development/phyloref/phyx.js/node_modules/mocha/lib/mocha.js
- /Users/gaurav/Development/phyloref/phyx.js/node_modules/mocha/index.js
- /Users/gaurav/Development/phyloref/phyx.js/node_modules/mocha/bin/_mocha
```

As far as I can tell, this is because in the earlier versions, there were additional files alongside the `index.js` file in `node_modules/newick-js/dist`:

```
❯ ls node_modules/newick-js/dist/
index.d.ts index.js   src
```

However, in these later versions, these files are missing:

```
❯ ls node_modules/newick-js/dist/
index.js
```

Is this deliberate? Is there some other way I can use `require()` to get access to the `parse()` function from within my CommonJS code (https://github.com/phyloref/phyx.js/pull/127)? Any help would be hugely appreciated!

**Comment by keesey** [comment]
Sorry for the delay, I missed this report initially. I use TypeScript, so I haven't seen this -- looking into it....

**Comment by keesey** [comment]
Actually, wow, it was an error that would have occurred in TypeScript as well! I think I need to yank some builds. Install 1.2.1 -- that should do it.
